apiVersion: v1
kind: ReplicationController
metadata: 
  name: abhi-nginx-rc
spec:
  replicas: 2
  selector:
    app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec: 
      containers: 
      - name: abhi-nginx-container
        image: nginx
        ports:  
          - containerPort: 8080